export default {
  VALUE_CHANGED: 'VALUE_CHANGED',

  FINDING_STARTED: 'FINDING_STARTED',
  FINDING_SUCCESS: 'FINDING_SUCCESS',
  FINDING_FAILED: 'FINDING_FAILED',

  INSERT_ONE_STARTED: 'INSERT_ONE_STARTED',
  INSERT_ONE_SUCCESS: 'INSERT_ONE_SUCCESS',
  INSERT_ONE_FAILED: 'INSERT_ONE_FAILED',

  UPDATE_ONE_STARTED: 'UPDATE_ONE_STARTED',
  UPDATE_ONE_SUCCESS: 'UPDATE_ONE_SUCCESS',
  UPDATE_ONE_FAILED: 'UPDATE_ONE_FAILED',

  DELETE_ONE_STARTED: 'DELETE_ONE_STARTED',
  DELETE_ONE_SUCCESS: 'DELETE_ONE_SUCCESS',
  DELETE_ONE_FAILED: 'DELETE_ONE_FAILED',

  OBJECT_SELECTED: 'OBJECT_SELECTED',
  OBJECT_CREATED: 'OBJECT_CREATED',

  DATALIST_STARTED: 'DATALIST_STARTED',
  DATALIST_SUCCESS: 'DATALIST_SUCCESS',
  DATALIST_FAILED: 'DATALIST_FAILED',

  META_DATA_IS_SET:'META_DATA_IS_SET'
};
