export default {
  VALUE_CHANGED: 'VALUE_CHANGED',

  FINDING_STARTED: 'FINDING_STARTED',
  FINDING_SUCCESS: 'FINDING_SUCCESS',
  FINDING_FAILED: 'FINDING_FAILED',

  INSERT_ONE_STARTED: 'INSERT_ONE_STARTED',
  INSERT_ONE_SUCCESS: 'INSERT_ONE_SUCCESS',
  INSERT_ONE_FAILED: 'INSERT_ONE_FAILED',

  UPDATE_ONE_STARTED: 'UPDATE_ONE_STARTED',
  UPDATE_ONE_SUCCESS: 'UPDATE_ONE_SUCCESS',
  UPDATE_ONE_FAILED: 'UPDATE_ONE_FAILED',

  DELETE_ONE_STARTED: 'DELETE_ONE_STARTED',
  DELETE_ONE_SUCCESS: 'DELETE_ONE_SUCCESS',
  DELETE_ONE_FAILED: 'DELETE_ONE_FAILED',

  CREATE_OBJECT: 'CREATE_OBJECT'

  
};
