export default {
  DROPDOWN_FUCUSED: 'DROPDOWN_FUCUSED',
  DROPDOWN_FIND_SUCCESS: 'DROPDOWN_FIND_SUCCESS',
  DROPDOWN_FIND_FAILED: 'DROPDOWN_FIND_FAILED',
  DROPDOWN_ITEM_SELECTED: 'DROPDOWN_ITEM_SELECTED',
  DROPDOWN_MOUNTED: 'DROPDOWN_MOUNTED'
};
