export default {
  EMAIL: 'EMAIL',
  EMAIL_OR_USERNAME: 'EMAIL_OR_USERNAME',
  PASSWORD: 'PASSWORD',
  EMPTY_STRING: 'EMPTY_STRING',
  RANAGE: 'RANAGE',
  USERNAME: 'USERNAME',
  PASSWORD_MATCH: 'PASSWORD_MATCH'
};
export const serverValidationType = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  REGISTERED_EMAIL: 'REGISTERED_EMAIL',
  EMAIL_NOT_REGISTERED: 'EMAIL_NOT_REGISTERED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_USERNAME_OR_PASSWORD: 'INVALID_USERNAME_OR_PASSWORD',
  INVALID_EMPTY_STRING: 'INVALID_EMPTY_STRING'
};
