export default {
  VALUE_CHANGED: 'VALUE_CHANGED',
  LOGIN_STARTED: 'LOGIN_STARTED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  SIGNUP_STARTED: 'SIGNUP_STARTED',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILED: 'SIGNUP_FAILED',

  CHANGE_PASSWORD_STARTED: 'CHANGE_PASSWORD_STARTED',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',

  REQUEST_PASS_CHANGE_STARTED: 'REQUEST_PASS_CHANGE_STARTED',
  REQUEST_PASS_CHANGE_SUCCESS: 'REQUEST_PASS_CHANGE_SUCCESS',
  REQUEST_PASS_CHANGE_FAILED: 'REQUEST_PASS_CHANGE_FAILED',

  EMAIL_CONSTRAINT_NOT_VALID: 'EMAIL_CONSTRAINT_NOT_VALID',
  EMAIL_CONSTRAINT_VALID: 'EMAIL_CONSTRAINT_VALID',

  PASSWORD_CONSTRAINT_NOT_VALID: 'PASSWORD_CONSTRAINT_NOT_VALID',
  PASSWORD_CONSTRAINT_VALID: 'PASSWORD_CONSTRAINT_VALID',

  USERNAME_CONSTRAINT_VALID: 'USERNAME_CONSTRAINT_VALID',
  USERNAME_CONSTRAINT_NOT_VALID: 'USERNAME_CONSTRAINT_NOT_VALID',

  STRING_CONSTRAINT_VALID: 'STRING_CONSTRAINT_VALID',
  STRING_CONSTRAINT_NOT_VALID: 'STRING_CONSTRAINT_NOT_VALID',

  RESET_CONSTRAINT: 'RESET_CONSTRAINT'
};
